### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by androidcn** [01miaom/jiankangyizhan#1]
Thanks!!!bug can not run m1 macbook

**Comment by 01miaom** [comment]
Chrome can be used on m1, if you have installed the m1 version of Chromedrive in the corresponding folder, the drive is necessary, even if you have Chrome browser.  

Firefox browser has not yet launched the corresponding drive.

For Chrome browser, you can refer to the following link to install drive:
https://chromedriver.chromium.org/downloads

**Comment by androidcn** [comment]
https://github.com/sml2h3/ddddocr
install ddddocr

error
`
pip install ddddocr
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))': /simple/ddddocr/
Collecting ddddocr
  Using cached ddddocr-1.0.6-py3-none-any.whl (6.9 MB)
Collecting Pillow
  Using cached Pillow-9.0.1-1-cp310-cp310-macosx_11_0_arm64.whl (2.7 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ddddocr) (from versions: none)
ERROR: No matching distribution found for onnxruntime
`
[](https://github.com/sml2h3/ddddocr#%E5%AE%89%E8%A3%85%E5%91%BD%E4%BB%A4)暂时不支持Macbook M1(X)，M1(X)用户需要自己编译onnxruntime才可以使用

**Comment by 01miaom** [comment]
This part of the code is character recognition and can be replaced with any general ocr library or api. Such as easyocr in pip or baidu ai: https://ai.baidu.com/tech/ocr

**Comment by androidcn** [comment]
原来是ddddocr python 要求 3.9 我用了3.10
